### ISSUE TITLE
Add Terms page in UI in /auth/terms page

### ISSUE THREAD

**Issue by ambujraj** [ambujraj/ByteShare#111]
**Is your feature request related to a problem? Please describe.**
Need a terms of use page. 

**Describe the solution you'd like**
Add a simple terms page in path /auth/terms

Below is the terms page content:
[TERMS.md](https://github.com/ambujraj/ByteShare/files/14822231/TERMS.md)

**Comment by frtug** [comment]
Yeah, it looks good. I think these terms are necessary and can protect the enterprise from legal actions.

**Comment by ambujraj** [comment]
Sure, I will assign this to you.
