### ISSUE TITLE
Header dropdown not opening in mobile version.

### ISSUE THREAD

**Issue by ambujraj** [ambujraj/ByteShare#129]
**Describe the bug**
The dropdown is not opening in case of mobile version in header.

**To Reproduce**
1. Go to ByteShare.io
2. Click on hamburger in mobile version

**Expected behavior**
The hamburger should expand to show header buttons

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS 17.3.1
 - Browser: safari

**Comment by frtug** [comment]
okay, I am taking a look

**Comment by frtug** [comment]
I thought this an quick fix issue but i see some code missing here and some code got repeated. I need to clean and update it. Will done tomorrow

**Comment by ambujraj** [comment]
Sure @frtug 👍🏼
