### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by ambujraj** [ambujraj/ByteShare#88]
**Is your feature request related to a problem? Please describe.**
improve the UI look to make it better.

**Describe the solution you'd like**
Redesigning the UI.

**Comment by frtug** [comment]
I am taking this. You can assign this to me.

**Comment by ambujraj** [comment]
Hi @frtug,

Thanks for taking that up.
I will assign that to you.

We will be discussing about the changes here.

**Comment by frtug** [comment]
Hi @ambujraj 
I need your help in setting up. I am seeing some issues when doing `terraform apply`. Can you walk me through, How can i setup in my local ?

**Comment by ambujraj** [comment]
@frtug Sure, let's connect on discord 
Discord ID: ambuj.raj

**Comment by frtug** [comment]
How this new ui looks ?
![Screenshot 2024-04-07 at 18 45 52](https://github.com/ambujraj/ByteShare/assets/32640258/1b2a73f3-873e-4940-90e6-aaeca94433cc)

**Comment by frtug** [comment]
![Uploading Screenshot 2024-04-07 at 23.09.38.png…]()

**Comment by frtug** [comment]
![Screenshot 2024-04-07 at 23 09 38](https://github.com/ambujraj/ByteShare/assets/32640258/5b68a8bd-7ef0-40f0-89fb-08d841ed9647)

**Comment by ambujraj** [comment]
@frtug Thanks for the design. This looks good. Although, there needs some updates in the UI

1. Make the icons and illustration smaller in size.
2. Take into account the mobile and tablet version of the app. The send button should be directly accessible without the need of scrolling for the end user.

**Comment by frtug** [comment]
okay, considered these remarks.
