### ISSUE TITLE
Unable to access email text field,also allow to add email directly through options 

### ISSUE THREAD

**Issue by jeevikasirwani** [ambujraj/ByteShare#93]
**Describe the bug**

**To Reproduce**
1. Go to 'https://byteshare.io/'
2. Click on 'Send files'
3. See error

**Expected behavior**
should allow to directly use email option and it should be able to take input on one click

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ambujraj** [comment]
@jeevikasirwani Thanks for the contribution. 

Can you please attach any screenshot or elaborate the issue

**Comment by ambujraj** [comment]
Hi,

Fixed the issue you reported in
Issue: #94

Please check once. 

Also, thanks for the pointing that out.

**Comment by jeevikasirwani** [comment]
just checked....it works 👍
